repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: alloy
    namespace: monitoring
    chart: grafana/alloy
    version: 0.9.1
    values:
      - values.yaml