# Crossplane Helm Values
# Infrastructure as Code for Kubernetes
customLabels:
  team: platform
  owner: team-platform
  cost-center: internal-platform
  env: prod
  system: infra
  service: crossplane
  
# Enable webhooks
webhooks:
  enabled: true

# RBAC settings  
rbacManager:
  enabled: true
  managementPolicy: All

# Enable package manager forpackages:
  enabled: true
