apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: trip-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - trip-app
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  podMetricsEndpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 30s