apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - tailscale-eks.yaml
  - secret-store-aws.yaml
  - network-policies.yaml

commonLabels:
  team: platform
  owner: team-platform
  system: eks-dr
