app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

proxy:
  endpoints:
    '/kubecost':
      target: http://kubecost-frontend.kubecost.svc.cluster.local:9090
      changeOrigin: true

    '/azure-openai':
      target: https://chatops-openai-ktcloud.cognitiveservices.azure.com
      changeOrigin: true
      credentials: dangerously-allow-unauthenticated
      headers:
        api-key: ${AZURE_OPENAI_API_KEY}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/service-wizard/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/aws-service-wizard/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/simple-server/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/infrastructure-only/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/aws-infrastructure/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/azure-service-wizard/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/azure-infrastructure/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/service/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/service-with-infra/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: k8s-idp
          url: https://kubernetes.default.svc
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: true

kubecost:
  baseUrl: /api/proxy/kubecost

permission:
  enabled: true