apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatops-bot-secret
  namespace: chatops
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore

  target:
    name: chatops-bot-secret
    creationPolicy: Owner

  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: DISCORD_TOKEN

    - secretKey: AZURE_OPENAI_KEY
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_KEY

    - secretKey: AZURE_OPENAI_ENDPOINT
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_ENDPOINT

    - secretKey: AZURE_OPENAI_MODEL
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_MODEL

    - secretKey: PROMETHEUS_URL
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: PROMETHEUS_URL