apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: gitops
  labels:
    managed-by: vault-eso
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: oidc.clientSecret
      remoteRef:
        key: k8s/gitops/argocd-oidc-secret
        property: clientSecret
