apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-postgresql
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/backstage/backstage-postgresql
