apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatops-bot-secret
  namespace: chatops
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: chatops-bot-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/chatops/chatops-bot-secret
