apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-oidc-secrets
  namespace: auth
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: dex-oidc-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/auth/dex-oidc-secrets
