apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/monitoring/grafana-oauth-secret
