apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-target-secret
  namespace: longhorn-system
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-target-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/longhorn-system/longhorn-backup-target-secret
