apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio-storage
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/minio-storage/minio-credentials
