apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-longhorn
  namespace: longhorn-system
  labels:
    managed-by: vault-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-longhorn
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/longhorn-system/oauth2-proxy-longhorn
