apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/helm-releases/grafana
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
