# Kubernetes Namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    name: auth
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: security       # Security Engineer 담당
    cost_center: internal-platform
    env: prod
    system: platform
    service: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
  labels:
    name: secrets
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: security       # Security Engineer 담당
    cost_center: internal-platform
    env: prod
    system: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  labels:
    name: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: platform       # Platform Lead 담당
    cost_center: internal-platform
    env: prod
    system: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: sre            # SRE / Observability 담당
    cost_center: internal-platform
    env: prod
    system: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
  labels:
    name: kubecost
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: finops         # FinOps Engineer 담당
    cost_center: internal-platform
    env: prod
    system: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    name: crossplane-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: platform       # Platform Lead 담당
    cost_center: internal-platform
    env: prod
    system: platform
