# Kubernetes Namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    name: auth
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: security
    cost-center: internal-platform
    environment: prod
    system: security
    service: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
  labels:
    name: secrets
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: security
    cost-center: internal-platform
    environment: prod
    system: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  labels:
    name: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: platform-lead
    cost-center: internal-platform
    environment: prod
    system: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: sre
    cost-center: internal-platform
    environment: prod
    system: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
  labels:
    name: kubecost
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: finops
    cost-center: internal-platform
    environment: prod
    system: finops
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    name: crossplane-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: platform-lead
    cost-center: internal-platform
    environment: prod
    system: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    name: backstage
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: platform
    owner: finops
    cost-center: internal-platform
    environment: prod
    system: platform
