apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dex-pdb.yaml
  - argocd-server-pdb.yaml
  - argocd-application-controller-pdb.yaml
  - argocd-repo-server-pdb.yaml
  - backstage-backend-pdb.yaml
  - minio-pdb.yaml
