# Grafana with Dex OAuth
# Helmfile release definition

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.10.1
    values:
      - values.yaml
