{
 "title": "Kubernetes All-in-one Cluster Monitoring ko_KR",
 "description": "This dashboard is the education purpose for the Grafana panel and other functions. Thus it cannot be guaranteed for other environment. ",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "query": {
     "query": "query_result(node_uname_info{nodename=\"$node\"})"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "클러스터 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "컨트롤 플레인 컴포넌트 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n    avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.cilium.*|.*.hubble.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n    /\n    count without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.cilium.*|.*.hubble.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[5m:2m])\n)"
    }
   ]
  },
  {
   "title": "노드 현황",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": "count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"})"
    },
    {
     "expr": "max by(node) (\n  max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}\n)\n"
    },
    {
     "expr": "sum by (node) (\n    label_replace(\n        instance:node_cpu:ratio + on(instance) group_left(nodename) node_uname_info,\n        \"node\",\n        \"$1\",\n        \"nodename\", \n        \"(.+)\"\n    )\n) \n/\nsum by (node) (kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "avg by (node) (time() - node_boot_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 서버 응답 속도(P99, duration: $duration)",
   "type": "stat",
   "description": "API 요청에 대한 kube-apiserver의 P99(하위 1%) 평균 응답 속도:<br>\n이 값이 높을 수록 성능에 문제가 있을 수 있습니다<br>\nduration을 증가시키면 일시적인 급변동의 영향이 완화됩니다.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{scope=\"\"}[$duration])) by (scope, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daemonset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_status_current_number_scheduled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LoadBalancer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_spec_type{type=\"LoadBalancer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네임스페이스 별 파드 개수",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 별 파드 개수",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info) by (node)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "파드 상태 종합",
   "type": "stat",
   "description": "개별 파드의 상태:<br>\n15분 기준의 재시작 횟수+상태 이상 횟수를 평균하여 이상 여부를 탐지합니다.<br>\nGood: 15분 이내 상태 이상 없음<br>\nWarn: 15분 이내 상태 이상 평균 2회 미만</br>\nBad: 15분 이내 상태 이상 평균 2회 이상",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod, namespace)(\r\n    (\r\n    sum by (pod, namespace) (increase(kube_pod_container_status_waiting{reason!~\"ContainerCreating\"}[15m]))\r\n    +\r\n    sum by (pod, namespace) (increase(kube_pod_container_status_restarts_total[15m]))\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "현재 파드 상태",
   "type": "stat",
   "description": "현재 파드의 상태:<br>\nCrashLoopBackOff - 오류가 있어 재시작을 시도했지만 실패한 파드입니다. 로그를 통해 오류를 파악하세요.<br>\nOrphaned - 쿠버네티스 컨트롤러의 관리에서 벗어나 고아 상태로 존재하는 파드입니다. 수동 조치가 필요합니다.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "Total" },
    {
     "expr": "count(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"})",
     "legendFormat": "CrashLoopBackOff"
    },
    {
     "expr": "sum(increase(kubelet_orphaned_runtime_pods_total[5m]))",
     "legendFormat": "Orphaned"
    }
   ]
  },
  { "title": "전체 클러스터", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "노드 별 CPU 사용률(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", instance=\"$instance\"}[2m])) / count by (instance)(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"})",
     "legendFormat": "{{node}} "
    }
   ]
  },
  {
   "title": "노드 별 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes + on(instance) group_left(nodename) node_uname_info) \n- \n(node_memory_MemAvailable_bytes + on(instance) group_left(nodename) node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽 (duration: $duration)",
   "type": "timeseries",
   "description": "초당 네트워크 트래픽:<br>\nduration 기간동안 클러스터가 송/수신한 네트워크 트래픽의 변화량 기반으로 초당 네트워크 트래픽을 계산한 값입니다<br>\n급격한 변동을 감지하기 위해서는 duration을 작게하고, 장기 추세를 감지하기 위해서는 duration을 크게 합니다.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(node_network_receive_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(in)"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(out)"
    }
   ]
  },
  {
   "title": "API 서버 호출 빈도 (duration: $duration)",
   "type": "heatmap",
   "description": "API 서버 호출 빈도:<br>\nduration 기간 동안 API서버 호출 빈도의 변화량을 기반으로 계산한 초당 API 서버 호출 빈도를 행위(verb)별로 분류한 값입니다.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$duration]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  { "title": "노드 $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", instance=\"$instance\"}[2m])) / count by (instance)(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "메모리 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}) / node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "디스크 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(node_filesystem_size_bytes{instance=\"$instance\"} - node_filesystem_avail_bytes{instance=\"$instance\"}) / sum by (instance)(node_filesystem_size_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU 코어",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "File descriptor / Context switches",
   "type": "timeseries",
   "description": "File descriptor / Context switches:<br>\n시스템의 처리 성능에 중요한 File descriptor 숫자와 Context Switch 빈도입니다.<br>\nfilefd - 시스템에서 파일 작업이나 네트워크 연결 작업이 할당된 수를 의미합니다. 이 지표가 급격히 증가하면 이와 같은 작업이 늘어나고 있다는 의미입니다.<br>\nswitches - 시스템이 프로세스와 스레드를 전환하는 횟수입니다. 작업량 증가로 인한 프로세스 간 경쟁, 과도한 프로세스 생성으로 인해 상승할 수 있습니다.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOPS 완료 (duration: $duration)",
   "type": "timeseries",
   "description": "Disk IOPS 완료:<br>\nduration 기간 동안 Disk의 읽기/쓰기 작업이 완료된 횟수를 기반으로 계산한 초당 I/O 성능 지표입니다.<br>\n읽기/쓰기 작업이 증가 때 변할 수 있으며 이 값의 변동폭이 클 경우 디스크의 성능이 불안정함을 의미합니다.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{node=~\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\",node=\"$node\"}"
    }
   ]
  },
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_ips{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Pod IP"
    }
   ]
  },
  {
   "title": "Pod 가동 상태",
   "type": "stat",
   "description": "Pod 가동 상태:<br>\n15분 기준의 재시작 횟수+상태 이상 횟수를 평균하여 이상 여부를 탐지합니다.<br>\nGood: 15분 이내 상태 이상 없음<br>\nWarn: 15분 이내 상태 이상 평균 2회 미만</br>\nBad: 15분 이내 상태 이상 평균 2회 이상",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod, namespace)(\r\n    (sum by (pod, namespace) (increase(kube_pod_container_status_waiting{pod=\"$pod\", namespace=\"$namespace\", reason!~\"ContainerCreating\"}[15m]))\r\n    +\r\n    sum by (pod, namespace) (increase(kube_pod_container_status_restarts_total{pod=\"$pod\", namespace=\"$namespace\"}[15m]))\r\n    )\r\n)"
    }
   ]
  },
  {
   "title": "PVC 사용률(%)",
   "type": "stat",
   "description": "PVC 사용률(%):<br>\n파드에 마운트 된 PVC의 사용률을 계산합니다. 단 NFS의 경우 NFS 서버 전체의 사용률 반환하므로 동일한 NFS 서버를 사용하는 PVC 간의 사용률이 같게 나올 수 있습니다.",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    sum by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"})\r\n    /\r\n    sum by (persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\r\n  )\r\n  * \r\n  on (persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\", namespace=\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC 정보",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info\r\n* \r\non (persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 할당 제한",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "리소스 사용량",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"$namespace\"}[2m]))",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "Memory(bytes)"
    }
   ]
  },
  {
   "title": "Pod 생성시간",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "15분 이내 재시작",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[15m])))"
    }
   ]
  },
  {
   "title": "메모리 할당 제한",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "메모리 상태(Swap/Failure)",
   "type": "timeseries",
   "description": "Swap / Memory Failure<br>\n파드의 메모리 문제를 확인하는데 중요한 스왑과  메모리 할당 실패에 대한 값입니다.<br>\nSwap - 파드가 할당된 메모리 값 이상을 사용하여 디스크를 사용한 크기입니다. 클러스터에서 Swap 은 비활성화하는 경우가 많아 대부분의 경우 0이지만 Swap이 활성화 된 경우 이 값의 증가는 메모리 부족으로 인한 비정상 종료로 이어질 수 있습니다.<br>\nMemory Failure - 컨테이너가 메모리를 할당 받으려 요청했으나 실패한 횟수입니다. 컨테이너에서 사용할 수 있는 메모리 제한을 초과하여 메모리를 요청할 때 발생합니다. 이 값이 계속 증가하는 경우 내부 애플리케이션이 GC(Garbage Collection)을 과도하게 수행 중이거나 메모리 할당을 대기하며 블로킹(Blocking)에 빠진 상태일 수 있습니다.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_swap{pod=\"$pod\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum by (pod) (rate(container_memory_failcnt{pod=\"$pod\"}[5m]))",
     "legendFormat": "Memory Failure"
    }
   ]
  },
  {
   "title": "스레드 개수",
   "type": "timeseries",
   "description": "스레드 개수:<br>\n컨테이너 내부에서 실행 중인 스레드 숫자입니다. <br>\n스레드 숫자가 증가하지 않는데 CPU 사용량이 급격히 증가한다면 특정 스레드가 병목 현상(Bottleneck)을 겪고 있을 가능성이 있습니다<br>\n쓰레드 숫자가 급격히 증가하는데 CPU 사용량이 늘지 않는다면 스레드가 수행하는 작업이 블로킹(Blocking)에 빠졌을 가능성이 있습니다.",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_threads{pod=\"$pod\", namespace=\"$namespace\", container!=\"POD\"})",
     "legendFormat": "Thread"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽 (duration: $duration)",
   "type": "timeseries",
   "description": "초당 네트워크 트래픽:<br>\nduration 기간동안 파드가 송/수신한 네트워크 트래픽의 변화량 기반으로 초당 네트워크 트래픽을 계산한 값입니다<br>\n급격한 변동을 감지하기 위해서는 duration을 작게하고, 장기 추세를 감지하기 위해서는 duration을 크게 합니다.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  }
 ]
}