# Longhorn Storage Configuration
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    team: platform
    owner: platform-lead
    cost_center: internal-platform
    env: production
    system: infra
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataEngine: "v1"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    team: platform
    owner: platform-lead    
    cost_center: internal-platform
    env: production
    system: infra
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
