apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dest-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: dest-secret
  data:
    - secretKey: my-value# 생성될 K8S Secret의 key
      remoteRef:
        key: sydk# Vault 내 Secret 경로
        property: t34m# Vault Secret의 특정 property
