apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret" # 'vault secrets list'에 나온 그 이름
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes" # 'vault auth list'에 나온 그 이름
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
~                                                                                                   
~                                         
