apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dest-secret
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: dest-secret
    creationPolicy: Owner
  data:
    - secretKey: my-value
      remoteRef:
        key: sydk
        property: t34m
