apiVersion: v1
kind: Service
metadata:
  name: trip-backend-service
spec:
  type: NodePort 
  selector:
    app: trip-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-backend
  template:
    metadata:
      labels:
        app: trip-backend
    spec:
      containers:
      - name: trip-backend
        image: junho010712/trip-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://trip-db:5432/trip_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1771" # DB 설정과 일치시킨 비밀번호입니다.
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "none"
