apiVersion: v1
kind: Service
metadata:
  name: trip-main-service
spec:
  type: LoadBalancer # 외부에서 3000포트로 접속하기 위해 설정
  selector:
    app: trip-main
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-main
  template:
    metadata:
      labels:
        app: trip-main
    spec:
      containers:
      - name: trip-main
        image: junho010712/trip-front:latest
        env:
        - name: VITE_SERVICE_NAME
          value: "MAIN_PORTAL"
        ports:
        - containerPort: 80