spring.application.name=goorm-trip

# 외부 API 설정
external.api.tour.base-url=https://apis.data.go.kr/B551011/KorService2

# supabase DB
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.fzojujaodydonzmklhgx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.profiles.include=secret

management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

management.metrics.distribution.percentiles-histogram.http.server.requests=true
trip.chain.enabled=${TRIP_CHAIN_ENABLED:false}
trip.cart-api.base-url=${TRIP_CART_API_BASE_URL:http://localhost:8081}
trip.payment-api.base-url=${TRIP_PAYMENT_API_BASE_URL:http://localhost:8082}
