apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-idp-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        actions-runner: ""
    spec:
      repository: sydk-ktcloud/k8s-idp
      labels:
        - self-hosted
        - k8s-idp
      image: summerwind/actions-runner:v2.333.1-ubuntu-24.04
      serviceAccountName: actions-runner
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
