apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.k8s-idp.example.org
spec:
  group: k8s-idp.example.org
  names:
    kind: XBucket
    plural: xbuckets
    singular: xbucket
  claimNames:
    kind: Bucket
    plural: buckets
    singular: bucket
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the GCS bucket
                location:
                  type: string
                  description: Bucket location
                  default: US
                storageClass:
                  type: string
                  description: Storage class
                  default: STANDARD
                versioning:
                  type: boolean
                  description: Enable versioning
                  default: false
              required:
                - name
