apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.7
      helm:
        valueFiles:
          - $values/kubernetes/helm-releases/argocd/values.yaml
    - repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
