apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/helm-releases/crossplane
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
