apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-burst-vpn
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/manifests/gke-burst
    directory:
      recurse: false
      include: "tailscale-gke.yaml"
  destination:
    server: https://34.47.90.121
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
