apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-idp
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/argocd-apps
    directory:
      recurse: true
      exclude:
        - k8s-idp.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
