apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: kubecost
    app.kubernetes.io/component: finops
spec:
  project: default
  sources:
    - repoURL: https://kubecost.github.io/kubecost/
      chart: kubecost
      targetRevision: 3.1.5
      helm:
        valueFiles:
          - $values/kubernetes/helm-releases/kubecost/values.yaml
    - repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
