apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-oauth-proxy
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/manifests/kubecost-oauth-proxy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
