apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lifecycle-scanner
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: lifecycle-scanner
    app.kubernetes.io/component: lifecycle
spec:
  project: default
  source:
    repoURL: https://github.com/sydk-ktcloud/k8s-idp.git
    path: kubernetes/manifests/lifecycle-scanner
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
