---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lifecycle-scanner
  namespace: gitops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lifecycle-scanner
rules:
  - apiGroups:
      - k8s-idp.example.org
    resources:
      - clusters
      - databases
      - buckets
      - gcpinstances
      - ec2instances
      - s3buckets
      - eksclusters
      - rdsdatabases
      - azurevms
      - azureblobstorages
      - aksclusters
      - azuredatabases
      - webapps
      - pubsubs
    verbs:
      - get
      - list
      - watch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lifecycle-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lifecycle-scanner
subjects:
  - kind: ServiceAccount
    name: lifecycle-scanner
    namespace: gitops
