apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secret
  namespace: backstage
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore

  target:
    name: backstage-secret
    creationPolicy: Owner

  data:
    - secretKey: AZURE_OPENAI_API_KEY
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_KEY

    - secretKey: AZURE_OPENAI_ENDPOINT
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_ENDPOINT

    - secretKey: AZURE_OPENAI_MODEL
      remoteRef:
        key: k8s/chatops/chatops-bot-secret
        property: AZURE_OPENAI_MODEL