spring.application.name=trip-payment-api
server.port=${SERVER_PORT:8082}
spring.jackson.property-naming-strategy=SNAKE_CASE
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.metrics.distribution.percentiles-histogram.http.server.requests=true
