apiVersion: v1
kind: Service
metadata:
  name: trip-backend-service
  namespace: trip-app
spec:
  # 외부 접속을 위해 ClusterIP에서 NodePort로 변경합니다.
  type: NodePort 
  selector:
    app: trip-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-backend
  namespace: trip-app
  labels:
    app: trip-backend
    team: platform
    owner: team-appdev
    cost-center: internal-platform
    env: prod
    system: trip-app
    service: trip-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-backend
  template:
    metadata:
      labels:
        app: trip-backend
        team: platform
        owner: team-appdev
        cost-center: internal-platform
        env: prod
        system: trip-app
        service: trip-backend
    spec:
      containers:
      - name: trip-backend
        image: kylekim1223/trip-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://trip-db:5432/trip_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1771" # DB 설정과 일치시킨 비밀번호입니다.
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "none"
        # --- 모니터링을 위한 OTel 설정 추가 ---
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.monitoring.svc.cluster.local:4317" 
        - name: OTEL_SERVICE_NAME
          value: "trip-backend-service"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_METRICS_EXPORTER
          value: "none" # 메트릭 전송 끄기
        - name: OTEL_LOGS_EXPORTER
          value: "none" # 로그 전송 끄기
