apiVersion: v1
kind: Service
metadata:
  name: trip-db
  namespace: trip-app
spec:
  selector:
    app: trip-db
  ports:
    - protocol: TCP
      port: 5432      # 서비스가 노출할 포트
      targetPort: 5432 # 컨테이너 내부 포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-db
  namespace: trip-app
  labels:
    app: trip-db
    team: platform
    owner: team-appdev
    cost-center: internal-platform
    env: prod
    system: trip-app
    service: trip-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-db
  template:
    metadata:
      labels:
        app: trip-db
        team: platform
        owner: team-appdev
        cost-center: internal-platform
        env: prod
        system: trip-app
        service: trip-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1771"
        - name: POSTGRES_DB
          value: "trip_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: sql-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: sql-volume
        configMap:
          name: db-init-sql