apiVersion: v1
kind: Service
metadata:
  name: trip-main-service
  namespace: trip-app
spec:
  type: NodePort # 외부에서 3000포트로 접속하기 위해 설정
  selector:
    app: trip-main
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30249
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-main
  namespace: trip-app
  labels:
    app: trip-main
    team: platform
    owner: team-appdev
    cost-center: internal-platform
    env: prod
    system: trip-app
    service: trip-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-main
  template:
    metadata:
      labels:
        app: trip-main
        team: platform
        owner: team-appdev
        cost-center: internal-platform
        env: prod
        system: trip-app
        service: trip-main
    spec:
      containers:
      - name: trip-main
        image: kylekim1223/trip-front:v1.0.0
        env:
        - name: VITE_SERVICE_NAME
          value: "MAIN_PORTAL"
        ports:
        - containerPort: 80
