apiVersion: v1
kind: Service
metadata:
  name: trip-payment-service
  namespace: trip-app
spec:
  type: NodePort 
  selector:
    app: trip-payment
  ports:
    - protocol: TCP
      port: 3002       # 외부 접속 포트
      targetPort: 80   # 컨테이너 내부 포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-payment
  namespace: trip-app
  labels:
    app: trip-payment
    team: platform
    owner: team-appdev
    cost-center: internal-platform
    env: prod
    system: trip-app
    service: trip-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-payment
  template:
    metadata:
      labels:
        app: trip-payment
        team: platform
        owner: team-appdev
        cost-center: internal-platform
        env: prod
        system: trip-app
        service: trip-payment
    spec:
      containers:
      - name: trip-payment
        image: kylekim1223/trip-front:latest
        env:
        - name: VITE_SERVICE_NAME
          value: "PAYMENT_SERVICE"
        ports:
        - containerPort: 80
