name: CI-CD Connectivity Success
on:
  push:
    branches: [ cicd ]

jobs:
  connectivity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # [추가] 로봇을 우리 팀 전용망(Headscale)에 합류시키기
      - name: Connect to Headscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.HEADSCALE_KEY }}
        env:
          # Headscale 사용 시에는 이 환경 변수를 명시해주는 것이 가장 확실합니다.
          TS_LOGIN_SERVER: http://218.55.202.191:9090

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    
      - name: Check K8s Connection
        run: kubectl get nodes