apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xekscluster.k8s-idp.example.org
  labels:
    provider: aws
    resource: eks
spec:
  compositeTypeRef:
    apiVersion: k8s-idp.example.org/v1alpha1
    kind: XEKSCluster
  resources:
    - name: eks-cluster
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            region: us-east-1
            roleArn: ""
            vpcConfig:
              - subnetIds: []
            tags:
              team: platform
              owner: team-platform
              cost-center: internal-platform
              env: prod
              system: infra
              managed-by: crossplane
              resource-type: eks-cluster
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.roleArn
          toFieldPath: spec.forProvider.roleArn
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.vpcConfig[0].subnetIds
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
    - name: eks-node-group
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: NodeGroup
        spec:
          forProvider:
            region: us-east-1
            clusterNameSelector:
              matchControllerRef: true
            nodeRoleArn: ""
            subnetIds: []
            scalingConfig:
              - desiredSize: 3
                minSize: 1
                maxSize: 10
            instanceTypes:
              - t3.medium
            tags:
              team: platform
              owner: team-platform
              managed-by: crossplane
              resource-type: eks-nodegroup
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.nodeRoleArn
          toFieldPath: spec.forProvider.nodeRoleArn
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.subnetIds
        - fromFieldPath: spec.nodeCount
          toFieldPath: spec.forProvider.scalingConfig[0].desiredSize
        - fromFieldPath: spec.instanceType
          toFieldPath: spec.forProvider.instanceTypes[0]
